# Generated by Django 3.0.5 on 2020-04-26 00:44

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyOb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('max_temp', models.DecimalField(decimal_places=1, max_digits=8)),
                ('min_temp', models.DecimalField(decimal_places=1, max_digits=8)),
                ('atob_temp', models.DecimalField(decimal_places=1, max_digits=8)),
                ('precip', models.DecimalField(decimal_places=2, max_digits=8)),
                ('snowfall', models.DecimalField(decimal_places=1, max_digits=8)),
                ('snowdepth', models.DecimalField(decimal_places=1, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyOb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('remarks', models.TextField()),
                ('csv_filepath', models.CharField(max_length=512)),
                ('max_temp', models.DecimalField(decimal_places=1, max_digits=8)),
                ('max_temp_dates', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.DateField(), size=None), size=None)),
                ('max_temp_avg', models.DecimalField(decimal_places=1, max_digits=8)),
                ('max_temp_grtr90_count', models.IntegerField()),
                ('max_temp_less32_count', models.IntegerField()),
                ('min_temp', models.DecimalField(decimal_places=1, max_digits=8)),
                ('min_temp_dates', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.DateField(), size=None), size=None)),
                ('min_temp_avg', models.DecimalField(decimal_places=1, max_digits=8)),
                ('min_temp_less32_count', models.IntegerField()),
                ('min_temp_less0_count', models.IntegerField()),
                ('avg_temp', models.DecimalField(decimal_places=1, max_digits=8)),
                ('avg_dfn', models.DecimalField(decimal_places=1, max_digits=8)),
                ('hdd_count', models.IntegerField()),
                ('cdd_count', models.IntegerField()),
                ('precip', models.DecimalField(decimal_places=2, max_digits=8)),
                ('precip_todate', models.DecimalField(decimal_places=2, max_digits=8)),
                ('precip_todate_dfn', models.DecimalField(decimal_places=2, max_digits=8)),
                ('grtst_precip', models.DecimalField(decimal_places=2, max_digits=8)),
                ('grtst_precip_dates', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.DateField(), size=None), size=None)),
                ('precip_grtrT', models.IntegerField()),
                ('precip_grtr01', models.IntegerField()),
                ('precip_grtr10', models.IntegerField()),
                ('precip_grtr50', models.IntegerField()),
                ('precip_grtr100', models.IntegerField()),
                ('sf', models.DecimalField(decimal_places=1, max_digits=8)),
                ('sf_todate', models.DecimalField(decimal_places=1, max_digits=8)),
                ('sf_todate_dfn', models.DecimalField(decimal_places=1, max_digits=8)),
                ('grtst_sf', models.DecimalField(decimal_places=1, max_digits=8)),
                ('grtst_sf_dates', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.DateField(), size=None), size=None)),
                ('sf_grtrT', models.IntegerField()),
                ('sf_grtr50', models.IntegerField()),
                ('sf_grtr100', models.IntegerField()),
                ('sf_grtr500', models.IntegerField()),
                ('sf_grtr1000', models.IntegerField()),
                ('grtst_sd', models.DecimalField(decimal_places=1, max_digits=8)),
                ('grtst_sd_dates', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.DateField(), size=None), size=None)),
                ('sd_grtrT', models.IntegerField()),
                ('sd_grtr50', models.IntegerField()),
                ('sd_grtr100', models.IntegerField()),
                ('sd_grtr500', models.IntegerField()),
                ('sd_grtr1000', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PeakFoliage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=256)),
                ('caption', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='SnowSeason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('season', models.CharField(max_length=16)),
                ('oct', models.DecimalField(decimal_places=1, max_digits=8)),
                ('nov', models.DecimalField(decimal_places=1, max_digits=8)),
                ('dec', models.DecimalField(decimal_places=1, max_digits=8)),
                ('jan', models.DecimalField(decimal_places=1, max_digits=8)),
                ('feb', models.DecimalField(decimal_places=1, max_digits=8)),
                ('mar', models.DecimalField(decimal_places=1, max_digits=8)),
                ('apr', models.DecimalField(decimal_places=1, max_digits=8)),
                ('may', models.DecimalField(decimal_places=1, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='SunsetLakeIceInIceOut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(max_length=16)),
                ('icein_date', models.DateField()),
                ('iceout_date', models.DateField()),
                ('duration', models.IntegerField()),
            ],
        ),
    ]
