# Generated by Django 3.0.5 on 2020-05-04 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monthlyob',
            old_name='sd_grtr50',
            new_name='sd_grtr1',
        ),
        migrations.RenameField(
            model_name='monthlyob',
            old_name='sd_grtr1000',
            new_name='sd_grtr12',
        ),
        migrations.RenameField(
            model_name='monthlyob',
            old_name='sd_grtr100',
            new_name='sd_grtr3',
        ),
        migrations.RenameField(
            model_name='monthlyob',
            old_name='sd_grtr500',
            new_name='sd_grtr6',
        ),
        migrations.RenameField(
            model_name='monthlyob',
            old_name='sf_grtr50',
            new_name='sf_grtr1',
        ),
        migrations.RenameField(
            model_name='monthlyob',
            old_name='sf_grtr1000',
            new_name='sf_grtr12',
        ),
        migrations.RenameField(
            model_name='monthlyob',
            old_name='sf_grtr100',
            new_name='sf_grtr3',
        ),
        migrations.RenameField(
            model_name='monthlyob',
            old_name='sf_grtr500',
            new_name='sf_grtr6',
        ),
        migrations.AddField(
            model_name='monthlyob',
            name='precip_dfn',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monthlyob',
            name='sd_grtr18',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monthlyob',
            name='sf_dfn',
            field=models.DecimalField(decimal_places=1, default=None, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monthlyob',
            name='sf_grtr18',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
