# Generated by Django 3.0.5 on 2020-05-10 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200504_0016'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monthlyob',
            old_name='avg_dfn',
            new_name='avg_temp_dfn',
        ),
        migrations.AddField(
            model_name='dailyob',
            name='csv_filepath',
            field=models.CharField(default='', max_length=512),
            preserve_default=False,
        ),
    ]
