# Generated by Django 3.0.5 on 2020-05-10 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200510_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyob',
            name='precip',
            field=models.DecimalField(decimal_places=3, max_digits=8),
        ),
        migrations.AlterField(
            model_name='dailyob',
            name='snowdepth',
            field=models.DecimalField(decimal_places=3, max_digits=8),
        ),
        migrations.AlterField(
            model_name='dailyob',
            name='snowfall',
            field=models.DecimalField(decimal_places=3, max_digits=8),
        ),
        migrations.AlterField(
            model_name='monthlyob',
            name='grtst_precip',
            field=models.DecimalField(decimal_places=3, max_digits=8),
        ),
        migrations.AlterField(
            model_name='monthlyob',
            name='grtst_sd',
            field=models.DecimalField(decimal_places=3, max_digits=8),
        ),
        migrations.AlterField(
            model_name='monthlyob',
            name='grtst_sf',
            field=models.DecimalField(decimal_places=3, max_digits=8),
        ),
        migrations.AlterField(
            model_name='monthlyob',
            name='precip',
            field=models.DecimalField(decimal_places=3, max_digits=8),
        ),
        migrations.AlterField(
            model_name='monthlyob',
            name='precip_dfn',
            field=models.DecimalField(decimal_places=3, max_digits=8),
        ),
        migrations.AlterField(
            model_name='monthlyob',
            name='precip_todate',
            field=models.DecimalField(decimal_places=3, max_digits=8),
        ),
        migrations.AlterField(
            model_name='monthlyob',
            name='precip_todate_dfn',
            field=models.DecimalField(decimal_places=3, max_digits=8),
        ),
        migrations.AlterField(
            model_name='monthlyob',
            name='sf',
            field=models.DecimalField(decimal_places=3, max_digits=8),
        ),
        migrations.AlterField(
            model_name='monthlyob',
            name='sf_dfn',
            field=models.DecimalField(decimal_places=3, max_digits=8),
        ),
        migrations.AlterField(
            model_name='monthlyob',
            name='sf_todate',
            field=models.DecimalField(decimal_places=3, max_digits=8),
        ),
        migrations.AlterField(
            model_name='monthlyob',
            name='sf_todate_dfn',
            field=models.DecimalField(decimal_places=3, max_digits=8),
        ),
    ]
