# Generated by Django 3.0.5 on 2020-05-23 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200510_2316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snowseason',
            name='date',
        ),
    ]
