# Generated by Django 3.0.5 on 2020-05-24 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_snowseason_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snowseason',
            name='apr',
            field=models.DecimalField(decimal_places=3, max_digits=8),
        ),
        migrations.AlterField(
            model_name='snowseason',
            name='dec',
            field=models.DecimalField(decimal_places=3, max_digits=8),
        ),
        migrations.AlterField(
            model_name='snowseason',
            name='feb',
            field=models.DecimalField(decimal_places=3, max_digits=8),
        ),
        migrations.AlterField(
            model_name='snowseason',
            name='jan',
            field=models.DecimalField(decimal_places=3, max_digits=8),
        ),
        migrations.AlterField(
            model_name='snowseason',
            name='mar',
            field=models.DecimalField(decimal_places=3, max_digits=8),
        ),
        migrations.AlterField(
            model_name='snowseason',
            name='may',
            field=models.DecimalField(decimal_places=3, max_digits=8),
        ),
        migrations.AlterField(
            model_name='snowseason',
            name='nov',
            field=models.DecimalField(decimal_places=3, max_digits=8),
        ),
        migrations.AlterField(
            model_name='snowseason',
            name='oct',
            field=models.DecimalField(decimal_places=3, max_digits=8),
        ),
    ]
